# Generated by Django 4.0.5 on 2022-10-22 17:00

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_profileimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='post_image')),
                ('caption', models.TextField()),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('like_quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
